### ISSUE TITLE
why this project and what's the difference to SecretAgent 

### ISSUE THREAD

**Issue by RonaldinhoL** [ulixee/hero#114]
i am from SecretAgent  issue, i saw SecretAgent  was not update

**Comment by blakebyrnes** [comment]
Hi @RonaldinhoL, we're in the process of releasing Hero, which is the next evolution of SecretAgent. We're still pulling important fixes back to SecretAgent, but trying to get Hero release as soon as we can. We'll have several posts about what's new/different, but the quick summary is SecretAgent was focused on anti-blocking, and Hero is focused on easily creating stable scraper scripts (ie, they react to page changes and redesigns, and are built with a series of development tools built into Chrome).

**Comment by blakebyrnes** [comment]
This is a list of some differences with a migration path.
https://ulixee.org/docs/hero/help/migration-guide
