### ISSUE TITLE
CreepJS/CloudFlare detection.

### ISSUE THREAD

**Issue by wireguard-dev** [ulixee/hero#144]
CreepJS: 
1. ServiceWorkerGlobalScope: Windows platformVersion 8.1.1 does not match user agent version Windows 8.1 (64-bit)
2. navigator.webdriver is on: true (webdriver in "undefined", when legit browser has "false")
3. deviceMemory: available memory 3.5Gb is greater than device memory 1GB.

CloudFlare: Can't bypass UAM page. (example: admin.kingblue.xyz)

**Comment by blakebyrnes** [comment]
All of this is complete apart from the Cloudflare site. I was not seeing success there. I think they might be using QUIC to complete the conversation, which is going to be a large effort. I'm going to split that off into a new ticket
