### ISSUE TITLE
User profile won't restore whe disableMitm is true 

### ISSUE THREAD

**Issue by Baker68** [ulixee/hero#147]
I am aware of `session.mitmRequestSession.interceptorHandlers` used to restore profiles ;
![image](https://user-images.githubusercontent.com/34166422/187744170-078fa59c-1dcf-4006-9210-b6435713f778.png)

The reason why I am reporting this is because reCAPTCHA requests are blocked when `disableMitm` is false (when MITM is enabled) and I can only login if I complete the reCAPTCHA ;

So now that I can login with MITM disabled , I can't restore the profile.

![image](https://user-images.githubusercontent.com/34166422/187745035-caa4f6e6-61e0-4ba5-a344-3eed9e9867a4.png)

**Comment by blakebyrnes** [comment]
Thanks for logging this. It's a known limitation of the current profiles with MITM, but I think we could work around it by intercepting with devtools instead of the mitm.
