### ISSUE TITLE
Ability to abort url request

### ISSUE THREAD

**Issue by jamesike** [ulixee/hero#164]
Hello,
I was wondering if there was a way to be able to intercept a URL request, and abort it before the request is able to be sent

**Comment by blakebyrnes** [comment]
This feature should be implemented by existing "request" events along with an "abort" function on them. We might need a mode here that "pauses" the request until a client responds with a continue or abort... This is a good place to also allow a "hook" to wait for the response body as a ReadableStream. 

NOTE: we need discussion on whether the default "request" event should active an "abort" feature or if that's an additional function.

NOTE 2: we could also consider implementing this as a reference plugin.

**Comment by GlenDC** [comment]
I agree that ideally this can be done as a plugin, which can be one of the available plugins in a ulixee-controlled repo/folder of plugins available for opt-in.

I also would very much like this, as it allows you to save on a lot of wasted resources, given how much unrequired crap most websites download in the background these days...

**Comment by blakebyrnes** [comment]
The shorter path for much of this need is to simply add a blockedResourceUrls as a config to Hero (series of regexes or strings). It's already part of the Mitm code and interceptorHandlers pattern, we just need the configuration. Maybe we should log this separately - I think it's the feature you want. 

A request interception plugin is a bit of a more advanced scenario where you need to block and/or modify post data, response data, etc. The only time you need the ability to just plain abort if we add the `blockedResourceUrls` is if you just don't know what the url will look like (or there are 2 good ones, and a 3rd bad one you want to block).

**Comment by GlenDC** [comment]
> I think it's the feature you want.

Sounds about right. Okay, let's go for that :)

**Comment by blakebyrnes** [comment]
Here's a good starting place: you can see the existing configs coming in (they'll need to be added to client): https://github.com/ulixee/hero/blob/f7b3d0d07931fd8e06b5c6fa8c8477a4577450e3/core/lib/Tab.ts#L820

Regexps will automatically traverse the connection, but for places where we match urls, it's usually allow plain strings too (an example of this is how we do `waitForResource`)

**Comment by rjbks** [comment]
`A request interception plugin is a bit of a more advanced scenario where you need to block and/or modify post data, response data, etc.`

If that's what I'm looking for, what a good starting point, assuming a plugin is the place to do this? Are there any specific examples I reference?

**Comment by blakebyrnes** [comment]
> My use case would be intercept a script resource, modify it and return the modified script.

I think we need to make some minor modifications to the current plugin structure to support this. Likely we should add an additional callback to the `beforeHttpRequest` and `beforeHttpResponse` calls that indicates you have handled request processing and would like to halt request processing.

If you simply need a temporary way around this, you can subscribe to new Session creation directly in HeroCore (note that this is a semi-internal api and is not documented because of that).

```
import HeroSession from '@ulixee/hero-core/lib/Session';

HeroSession.on('new', session => {
  session.mitmRequestSession.interceptorHandlers.push({
      urls: ['SCRIPT_URL', new RegExp('Or regex')],
      handlerFn(url, type, request, response) {
        response.end(`<YOUR SCRIPT>`);
        return true;
      },
    });
});
```

**Comment by GlenDC** [comment]
`blockedResourceUrls` is now available and exposed. Still have to add automated tests.

**Comment by rjbks** [comment]
> HeroCore.pool.on('agent-created', ({agent}) => {
>   agent.mitmRequestSession.interceptorHandlers.push({
>       urls: ['SCRIPT_URL', new RegExp('Or regex')],
>       handlerFn(url, type, request, response) {
>         response.end(`<YOUR SCRIPT>`);
>         return true;
>       },
>     });
> });

How would I then proceed to get the script contents by making the request from the browser tab context that originated the request? I can't seem to find anything in the agent object or the browserContext.
