### ISSUE TITLE
unhandled exception from TimeoutError originating from MITM Socket

### ISSUE THREAD

**Issue by GlenDC** [ulixee/hero#169]
My app which wraps both the Hero client and server crashes now and then with the `TimeOut Error` that seems to not be handled and which seems to originate from:

```
node_modules/mitm/lib/MitmRequestAgent.ts in MitmRequestAgent.createSocketConnection at line 172:5
```

While time out errors can bubble up from `goto` statements, I do not expect to see them for XHR calls that I do not even make, neither do I expect it to be unhandled and crashing my app.

**Comment by GlenDC** [comment]
@blakebyrnes this one does happen now and then, usually related to analytics (e.g. google or bing).

I also think it needs to move to an unblocked repo, as it's from there (agent I think?)

**Comment by blakebyrnes** [comment]
@GlenDC Do you have a full stack trace and/or session database for this? I'm not reproducing it in tests.

**Comment by GlenDC** [comment]
I'll send you the information over on Discord!

**Comment by GlenDC** [comment]
I suppose your fix will be available in next release. As this is currently the only bug that occurs frequently and the only one crashing my process, I am looking forward to test it and give you feedback @blakebyrnes.

Please let me know if there's anything more you need from me!

**Comment by blakebyrnes** [comment]
@GlenDC this is in the latest version. Let me know if we can close this out.

**Comment by GlenDC** [comment]
Can be closed (for now).
It seems to be fixed.

I am now at `alpha-14`.
