### ISSUE TITLE
How change variable of any HTML Element?

### ISSUE THREAD

**Issue by loss-and-quick** [ulixee/hero#187]
I want to change [value](https://ulixee.org/docs/hero/awaited-dom/html-input-element#value)  of HTMLInputElement and DOC says `Sets the current value of the control`
I used code as example below:
`input.value="test"`
But nothing changed

**Comment by blakebyrnes** [comment]
Thanks for your comment. The awaited dom is currently readonly. These docs are copied from msn and this is a documentation error we need to fix.

In the interim, you have a few options:
1. You can click/type in the field using the interaction methods of hero and the awaited dom. This option will appear the most human
2. If you need to set something in the dom to bypass interaction, you can use the execute-js plug-in listed in the docs

**Comment by loss-and-quick** [comment]
> Thanks for your comment. The awaited dom is currently readonly. These docs are copied from msn and this is a documentation error we need to fix.
> 
> In the interim, you have a few options:
> 
> 1. You can click/type in the field using the interaction methods of hero and the awaited dom. This option will appear the most human
> 2. If you need to set something in the dom to bypass interaction, you can use the execute-js plug-in listed in the docs

Thanks
