### ISSUE TITLE
Как отключить запись сессий?

### ISSUE THREAD

**Issue by dilmaev** [ulixee/hero#193]
Привет, как можно отключить запись сессий?

**Comment by loss-and-quick** [comment]
Пиши на инглише,скорее всего тебя не поймут

**Comment by blakebyrnes** [comment]
Thanks @loss-and-quick :) Looked it up on a translation site!

There's not currently a way in Hero to fully disable session recording as some of the feature-set uses the underlying recording. We have some developers cleaning up databases once they're finished with a scrape and know they don't need to examine errors that occurred. https://ulixee.org/docs/hero/advanced-concepts/sessions#managing-sessions
