### ISSUE TITLE
Proxy usage issues

### ISSUE THREAD

**Issue by b4shx0r** [ulixee/hero#212]
we configure hero with

`  const hero = new Hero({
    upstreamProxyUrl: "http://xxx:xxx@IP:PORT",
    showChrome: true,
    sessionKeepAlive: true,
    userProfile: profile,
  });`

(tested socks5 and http proxies)

and always getting this error:

`Caught error in script Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: {
    '0': 0,
    '1': 0,
    '2': 24,
    '3': 4,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0,
    '10': 5,
    '11': 0,
    '12': 16,
    '13': 0,
    '14': 0,
    '15': 0,
    '16': 3,
    '17': 0,
    '18': 0,
    '19': 0,
    '20': 250,
    '21': 0,
    '22': 6,
    '23': 0,
    '24': 16,
    '25': 1,
    '26': 64,
    '27': 0,
    '28': 4,
    '29': 0,
    '30': 16,
    '31': 0,
    '32': 0
`

what's the issue here - proxies working fine. any one else has these problem too?

is it possible the proxies don't handle the requests correctly?

**Comment by blakebyrnes** [comment]
Yes, I guess I closed the other issue too quickly. The proxies are fine, but the public ip masking services are using http2 suddenly, and it broke the apis. https://github.com/ulixee/hero/issues/210

**Comment by blakebyrnes** [comment]
Sorry! You should be able to follow the instructions in the other ticket(s)

**Comment by b4shx0r** [comment]
ah ok thank for that quick response - didn't see this other issue ;) will wait for the fix thanks!

**Comment by blakebyrnes** [comment]
Disabled in version 2.0.0-alpha.18 by default
