### ISSUE TITLE
Concept of copy-paste/one shot instead of type for interactions

### ISSUE THREAD

**Issue by melehin** [ulixee/hero#224]
Hi!

I want to put a long text to textarea field.
```hero.interact({'type': '.....long text here....'})``` takes a lot of time...

Is there a way to speedup it or put text into textarea as one shot?

I see one way only. It's execute JS code like this:
```script
$("textarea").val('.....long text here....');
```
or
```script
document.getElementById('textarea').value = '.....long text here....';
```

**Comment by blakebyrnes** [comment]
Hi @melehin, check out this issue for some details on improving speed: https://github.com/ulixee/hero/issues/138

**Comment by melehin** [comment]
Thx a lot!
