### ISSUE TITLE
sessionPersistence: false  doesn't work with pm2

### ISSUE THREAD

**Issue by paulosllvn** [ulixee/hero#232]
Title says it all, worth testing it out using pm2.

**Comment by blakebyrnes** [comment]
Hi @paulosllvn, thanks for your report. Are you seeing it work without pm2? Could you include what version of hero you're using, what OS, and what version of node?

If possible, a small example showing what you're seeing would be very helpful!

**Comment by blakebyrnes** [comment]
Per comments on discord, this appears to be an issue with being on the wrong version
