### ISSUE TITLE
@ulixee/commons doesn't download with npm install

### ISSUE THREAD

**Issue by vbt123** [ulixee/hero#233]
I have tried deleting node modules and re installing a lot. No luck getting the commons folder.

**Comment by vbt123** [comment]
![image](https://github.com/ulixee/hero/assets/133582301/3135a542-40e9-4c6f-b1fe-7b09d7179bdf)

**Comment by vbt123** [comment]
On further inspection, looks like i still need to keep miner even though cloud has taken its place? Commons appears if i install miner

**Comment by blakebyrnes** [comment]
Is there anything here to fix? It might help to try out the npm commands to list commons. Sometimes they get nested under other folders in node modules if you're just looking in the directories.
