### ISSUE TITLE
exportUserProfile fails when userProfile is loaded via userProfile option

### ISSUE THREAD

**Issue by Baker68** [ulixee/hero#240]
Using the same project structure specified [here](https://github.com/ulixee/hero/issues/239), when the `userProfile` option is used, the `exportUserProfile` fails with error 
```
TypeError: window.exportDomStorage is not a function
```
In order to reproduce this issue you should export the user profile then load it via `userProfile` option then try to export it again (after some surfing).

**Comment by blakebyrnes** [comment]
We have several tests and users using this feature and having it operate correctly. Can you give me more details on the exact flow that's failing for you? Are you manually navigating around chrome? Are you disabling javascript?

**Comment by blakebyrnes** [comment]
Does this happen for you on every url? It seems unlikely to be related to the transport, but could very easily be the state of the page when you're exporting. Perhaps it's not fully loaded when you're making this call and we need to add some kind of wait inside the api?

**Comment by Baker68** [comment]
I have been doing some tests and it does seem to be related to the page state, but some times it even fails after waiting for AllContentLoaded.

I will keep you posted.
