### ISSUE TITLE
does the missing parts make it detectable?

### ISSUE THREAD

**Issue by boynet** [ulixee/hero#243]
Hi thanks for this great library, waiting to swap my puppeteer with this
I wonder since its in alpha and there is missing stuff like(from the [docs](https://ulixee.org/docs/hero/overview/basic-concepts))

- audio fingerprint (todo)
- fonts (todo)
- webgl / canvas (todo)

it means it still detectable?

**Comment by blakebyrnes** [comment]
Yes, those items are mostly about detecting your fingerprint on repeat visits, but they are definitely detectable and still todo. You can sort of work around these by running on the os you are emulating if you are having issues. Or you can run as all windows profiles, for instance. There are a number of other variables you can use to create "noise" in your profiles.
