### ISSUE TITLE
macOS ARM failed to install playground via npm

### ISSUE THREAD

**Issue by JobberRT** [ulixee/hero#244]
logs
```
prebuild-install http request GET https://github.com/WiseLibs/better-sqlite3/releases/download/v8.7.0/better-sqlite3-v8.7.0-node-v120-darwin-arm64.tar.gz
```

checked its release page, seems that `hero` is trying to use a no existing verison of `better-sqlite3`: https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.7.0 

Only node-115 is available, but hero tries to install node-120.

**Comment by blakebyrnes** [comment]
Ok, thanks! Likely your node version is > than the sqlite version that's on 8.7. I'll update in next release.
