### ISSUE TITLE
how to change user-agent in code?

### ISSUE THREAD

**Issue by tsung-sc** [ulixee/hero#247]
i've installed @ulixee/real-user-agents、@ulixee/chrome-104-0、@ulixee/chrome-105-0 and @ulixee/chrome-105-0,but i don't know how to use it.Can show me how to use it in code? i don't see any code in document! PLZ!

**Comment by blakebyrnes** [comment]
Did you come across this page? https://ulixee.org/docs/hero/advanced-client/user-agents

**Comment by tsung-sc** [comment]
> Did you come across this page? https://ulixee.org/docs/hero/advanced-client/user-agents

yes,i've read it many times,but i still don't know how to change user-agent in every new Hero instance.there is no code to show me how to use the library above.

**Comment by blakebyrnes** [comment]
new Hero({
  userAgent: '~ chrome >= 105 && windows >= 10'
});

**Comment by blakebyrnes** [comment]
That example is with a specific os. You can remove it if you want it to round robin. Is it not working?

**Comment by tsung-sc** [comment]
> That example is with a specific os. You can remove it if you want it to round robin. Is it not working?

I'm sorry that I didn't use this code again after installation, but it seems that the UA can be replaced now. But eventually I want to change the browser fingerprint. Is there any way?

**Comment by blakebyrnes** [comment]
That code will round robin between operating systems/versions and build versions of the chosen user agent. If you want to randomize the agent too, you can choose a range for your chrome versions

**Comment by blakebyrnes** [comment]
Just checking in. Did that answer your question?

**Comment by tsung-sc** [comment]
yes!thanks
