### ISSUE TITLE
Has been blocked by cloudflare

### ISSUE THREAD

**Issue by tsung-sc** [ulixee/hero#254]
Until yesterday, I could pass cloudflare's defense, but today suddenly all requests could not pass cloudflare's defense. The specific performance is that I always need to click to verify whether it is a real human, and cannot jump to the target page. It shouldn't be a problem with the proxy. My normal browser can pass the risk control smoothly. Could it be that cloudflare detected the signature?

**Comment by ducktype** [comment]
same here :(

**Comment by abhanan93** [comment]
Did you find any workaround for this?
