### ISSUE TITLE
TLS cert error on some websites.

### ISSUE THREAD

**Issue by JortsEnjoyer0** [ulixee/hero#270]
Apart from the "Not secure" red message in the left side of the address bar (with https crossed out) that is present when using Hero, some websites give this:

> Requested host does not match any Subject Alternative Names (SANs) on TLS certificate [46f00bd73610998027fac0e59ed15b53343184d63735d0aa3bb61db5edad0cfd] in use with this connection.
> 
> Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.

Which is from this site: https://www.simplyrecipes.com

The site works fine on a regular browser.

**Comment by blakebyrnes** [comment]
Hero runs with a Man in the Middle, so you are always going to get the not-secure flag. It has no impact on the page load or anything else that would be detectable, to my knowledge. 

For the SAN issue cause the content to not load?
