### ISSUE TITLE
Triple click (Google search for example)

### ISSUE THREAD

**Issue by NN-Binary** [ulixee/hero#272]
Hi!

I have an input text, I wish to erase the text in it (manually), to do that, I need to triple-click on the field and then type Backspace for as many char as there is, is there a way to do that?

Thank you guys~!

**Comment by blakebyrnes** [comment]
This is the easiest option: https://ulixee.org/docs/hero/basic-client/awaited-dom-extensions#clear-value

If that works, please mark this one as closed. Thanks!
