### ISSUE TITLE
Simple full stack deployment inside of a docker

### ISSUE THREAD

**Issue by ydennisy** [ulixee/hero#282]
I have tried the various deployment options, but none work trouble free - I know this is alpha software, but would love to see a working example of a TS + Docker simple deployment.

Thanks!

**Comment by blakebyrnes** [comment]
Could you provide more details on what you're having issues with? If this is typescript, we had an issue with exporting the types correctly. You can add "skipLibCheck" to get it to compile. Otherwise, some errors and code is needed to be able to help out.
