### ISSUE TITLE
demo code not working 

### ISSUE THREAD

**Issue by nivzee** [ulixee/hero#288]
```
const Hero = require('@ulixee/hero-playground');

(async () => {
  const hero = new Hero();
  await hero.goto('https://example.org');
  const title = await hero.document.title;
  const intro = await hero.document.querySelector('p').textContent;
  await hero.close();
})();

```
i run demo code above above with `node 22`, but the error : 

**[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)**

Is likely a got the wrong version of Nodejs?

**Comment by blakebyrnes** [comment]
Sorry I never got back to this issue. Were you able to figure this out? Is this a node 22 issue? I don't think the puny code is likely breaking things. What other output do you see?

**Comment by gnori-zon** [comment]
must need for node v23.2.0
```js
import Hero from '@ulixee/hero-playground';
```
