### ISSUE TITLE
Ulixee Cloud failed to launch Chrome - open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory

### ISSUE THREAD

**Issue by AndriusCTR** [ulixee/hero#291]
Hi there,

I am trying to launch Hero on Digitalocean VPS. After installation it did work and everything seemed ok but after server reboot it won't start and I get this error:

 "message": "Ulixee Cloud failed to launch Chrome - Failed to launch Chrome! Cancel Pending Promise (Target.setAutoAttach): Target closed.\n\n\nSometimes a reason can be found in the Chrome Stderr logs:\n\t[0821/120719.300620:WARNING:chrome_main_linux.cc(80)] Read channel stable from /home/andrius/.cache/ulixee/chrome/124.0.6367.78/CHROME_VERSION_EXTRA\n\t[18891:18891:0821/120719.322023:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)\n\t[0821/120719.337537:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)\n\t[0821/120719.337722:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2). See Cloud console logs for details.",
  "name": "BrowserLaunchError",
  "isSandboxError": false,
  
Followed by stacktrace.

Any ideas why it is looking for a folder that does not exist?

Thanks

**Comment by AndriusCTR** [comment]
How can I manually specify chrome path in Hero?

**Comment by blakebyrnes** [comment]
You might need to run the deb installer that comes with chrome installs `sudo $(npx install-browser-deps)`. You can just use the `npx install-browser-deps` to see the path and cat it first if you want to verify what you're running.

You can also manually specify chrome per chrome version with CHROME_124_BIN=... (replace the version as needed)

**Comment by AndriusCTR** [comment]
> You might need to run the deb installer that comes with chrome installs `sudo $(npx install-browser-deps)`. You can just use the `npx install-browser-deps` to see the path and cat it first if you want to verify what you're running.
> 
> You can also manually specify chrome per chrome version with CHROME_124_BIN=... (replace the version as needed)

Apparently something has messed up on my server so I would like to completely remove everything and do the full clean install. However it seems I can't do that or I don't know how. What should I do to completely remove ulixee and start from zero? Ubuntu 24.04

Thank you!

**Comment by blakebyrnes** [comment]
You probably need to wipe the cache dir where chrome is located

https://ulixee.org/docs/hero/help/troubleshooting

**Comment by AndriusCTR** [comment]
> You probably need to wipe the cache dir where chrome is located. There should be a ulixee directory inside your cache (more about cache here)
> 
> https://ulixee.org/docs/hero/help/troubleshooting

Thanks. Did not find any info  on proper uninstall instruction there though... So what should I do?

Run `npm uninstall @ulixee/cloud` and delete Cache dir, that's it? 

Tried that, but did not help at all, installing again still throws the same error... Is there anything else I should wipe out?

**Comment by blakebyrnes** [comment]
Oh, assumed you meant after deleting node_modules you weren't sure what else to delete.

**Comment by AndriusCTR** [comment]
> Oh, assumed you meant after deleting node_modules you weren't sure what else to delete.

So uninstall node modules, delete cache dir and that's it?
