### ISSUE TITLE
CDP Runtime Detection Evasion (Cloudflare, DataDome)

### ISSUE THREAD

**Issue by ven0ms99** [ulixee/hero#296]
Ulixee Hero can be detected by Cloudflare and such easily with only a few lines of code, since it utilizes `cdpSession.send('Runtime.enable')` [here](https://github.com/ulixee/hero/blob/e5d8f8d1e90c7cebefae51b570ddb743ea8f39fe/puppet-chrome/lib/FramesManager.ts#L70).

DataDome even confidently published and explained this detection method thoroughly [2 months ago](https://datadome.co/threat-research/how-new-headless-chrome-the-cdp-signal-are-impacting-bot-detection/). They also created [a webpage](https://deviceandbrowserinfo.com/info_device) that can be used to test if CDP automation is detected.

**Solution**

> These changes also led to the creation of new anti-detect bot frameworks, such as [no driver](https://github.com/ultrafunkamsterdam/nodriver) being announced as the successor of [undetected ChromeDriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/), and [Selenium Driverless](https://github.com/kaliiiiiiiiii/Selenium-Driverless).
> 
> To avoid being detected, these bot development frameworks decided not to rely on ChromeDriver and Selenium. Instead, they implement all the usual automation functions using low-level CDP commands that do not leverage Runtime.enable.

Since these are python libraries I guess it's not straightforward for Ulixee to adapt. But the developers of rebrowser have published a patch [for puppeteer as well](https://github.com/rebrowser/rebrowser-patches). This is already used by libraries like [puppeteer-real-browser](https://github.com/zfcsoftware/puppeteer-real-browser). Maybe it should be incorporated into hero as well? Either way, a solution is needed urgently.

**Comment by blakebyrnes** [comment]
Thanks for the links! There's been some work underway about similar problems

**Comment by DJBen** [comment]
Hey folks, how's the progress of this?

**Comment by blakebyrnes** [comment]
Next release should be much better

**Comment by gster** [comment]
I just used (https://www.browserscan.net/) to test the latest release, and it Perfectly bypassed the detection of "Runtime.enable".

**Comment by ven0ms99** [comment]
I, too, can confirm that my target website, which is protected by Cloudflare, with v30 can now be scraped without any problems. All praise to @soundofspace 🙇‍♂️ This is fantastic.

**Comment by addame2** [comment]
How you test guys its not working at all 

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/1daa6132-2dac-4e0e-931c-937443989dc4" />

if needed I can send some one on telegram or email address thanks
