### ISSUE TITLE
Errors I got during installation...

### ISSUE THREAD

**Issue by A-UNSAL** [ulixee/hero#311]
npm WARN deprecated @substrate/connect@0.8.8: versions below 1.x are no longer maintained
npm ERR! code 1
npm ERR! path D:\apps\bismillahirrahmanirrahim\node_modules\better-sqlite3
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=21.7.1 runtime=node arch=x64 libc= platform=win32)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.7.1 | win32 | x64
...

**Comment by blakebyrnes** [comment]
Try node.js 20. The error is coming from trying to custom build the npm library bettersqlite since you're on a version that they don't have prebuilds for. Or you can try to get node-gyp to play nice with windows. There are various articles on the web about getting that running. It can be finicky.
