### ISSUE TITLE
"Screen resolution" - same value in each request

### ISSUE THREAD

**Issue by stargazer33** [ulixee/hero#323]
I'm testing my Hero program against these bot detection tools (other tools should return same results):
  https://abrahamjuliot.github.io/creepjs/
  https://deviceandbrowserinfo.com/info_device

results for 4 requests:

1.
Screen resolution	           1440x900 pixels
Available screen resolution	1440x875 pixels

2.
Screen resolution	            1440x900 pixels	
Available screen resolution	1440x852 pixels

3.
Screen resolution	            1440x900 pixels	
Available screen resolution	1440x875 pixels

4.
Screen resolution	            1440x900 pixels	
Available screen resolution	1440x875 pixels

What I see:

**1. Screen resolution does not change at all. This is not OK.**

**2. Available screen resolution changes only in one request from 4. This could be improved.**

**Comment by blakebyrnes** [comment]
This was a purposeful choice so that you don't trigger different screen layouts by hero automatically rotating these without user intervention. If you want to rotate screens, you can do so with the hero constructor. You should make sure to keep it the same though if you rotate sessions

**Comment by stargazer33** [comment]
>  If you want to rotate screens, you can do so with the hero constructor. 
OK, good to know.

@blakebyrnes what else should I "rotate" ?  (just discovered screen sized, but I could miss some other things)
