### ISSUE TITLE
Retrying Flowcommands

### ISSUE THREAD

**Issue by Denetor03** [ulixee/hero#327]
## Documentation
"Flow Commands can be nested within each other. If nested commands cannot be completed due to AwaitedDOM errors (interactions, DOM errors, DOM state timeouts), they will trigger the outermost block to be retried."

```javascript
await hero.flowCommand(async () => {
  await hero.querySelector('#modalPrompt').$click();
  await hero.querySelector('#field1').$type('text');
}, assert => {
  assert(hero.querySelector('#field1').value, 'text'); // if false, 1. Prompt FlowHandlers, 2. Retry Command
});
```
## What I Tried

```javascript
await hero.activeTab.flowCommand(async () => {
    await hero.activeTab.flowCommand(async () => {
        // stuff
    });
    await hero.activeTab.flowCommand(async () => {
        // stuff
    }, assert => {
        let test = null;
        try {
            test = hero.document.querySelector("#pass1");
        } catch (e) {
            // handle error if needed
        }
        assert(test, null);
    }, { maxRetries: 3 });
}, { maxRetries: 3 });
```
## Error 
```bash
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: The FlowCommand cannot be completed. The Exit State is not satisfied and no FlowHandlers were triggered.
```

I'm not sure if I've just implemented it wrong or if I don't understand how Flow Commands work. Based on the documentation, I thought that it would retry the outer block until the max retries are reached.

**Comment by blakebyrnes** [comment]
You should be able to nest them, but your commands don't have synchronous tests, which is probably whey they're not triggering. You have to imagine handing off a "clause" to the browser page js env that you want it to check for. There's a flow test example here: https://github.com/ulixee/hero/blob/349056567761f2c94812f413ea7e5f86a927c47b/end-to-end/test/flow.test.ts#L333

**Comment by Denetor03** [comment]
I am able to nest them, but my concern is with the retrying feature.
Basically, if something fails (not a test), instead of triggering a flow handler, it should retry the outermost block. As described in the documentation:

"If nested commands cannot be completed due to AwaitedDOM errors (interactions, DOM errors, DOM state timeouts), they will trigger the outermost block to be retried."
