### ISSUE TITLE
Time Travel

### ISSUE THREAD

**Issue by sriraj66** [ulixee/hero#329]
Is there any clear Documentation about how it works or any docs for the code base ?

**Comment by blakebyrnes** [comment]
There are a few uses of Timetravel in the internal codebase, but it's not really for external consumption yet.

Uses:
- Replay in [Ulixee Desktop](https://github.com/ulixee/desktop)
- Detached Elements/Resources/Snippets (https://ulixee.org/docs/hero/advanced-client/detached-elements)
- Crawlers in Datastores (https://ulixee.org/docs/datastore/basics/crawler)
