### ISSUE TITLE
Can Hero Core Run on ARM Architecture Linux Servers or Windows?

### ISSUE THREAD

**Issue by yuri2peter** [ulixee/hero#332]
Hi there,

I'm interested in deploying Hero Core on different platforms and wanted to know if it supports:

- ARM Architecture Linux Servers
- Windows OS
Could you provide some guidance or documentation on how to set up Hero Core on these platforms, or confirm if there are any known limitations?

Thanks in advance for your assistance!

**Comment by blakebyrnes** [comment]
Windows OS, yes. Would love to support ARM but there aren't Chrome binaries for it (only Chromium). You can swap out Chrome for Chromium, but a lot of the emulation code/data files are expecting to run on Chrome

**Comment by yuri2peter** [comment]
I'm sorry to hear that ARM architecture is not supported. I understand the situation now—thank you for your response.
