### ISSUE TITLE
Package is not in node_modules

### ISSUE THREAD

**Issue by knaitas** [ulixee/hero#96]
Installation doesn't work, upon installing via yarn or npm, ulixee-hero is nowhere in node_modules:

![image](https://user-images.githubusercontent.com/29448167/155499602-89b251ee-fe3b-4766-aeec-82b0958c74b5.png)

**Comment by blakebyrnes** [comment]
@knaitas We haven't published hero to npm yet! Still working on it, but should have a version soon. You can use SecretAgent in the short term - it has a very similar api.

**Comment by knaitas** [comment]
Ok thanks!
